Script started on Fri 29 May 2015 10:08:18 PM PDT
~
jdixo001@hammer $ cd Documents/rshell
~/Documents/rshell
jdixo001@hammer $ bin/rshell
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ #begin, ls will be used to show contents of each new directory
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ cd bin
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/bin $ ls
cp  ls	mv  rm	rshell
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/bin $ cd ..
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ ls
a.out  bin  infinite.cpp  LICENSE  Makefile  README.md	src  tests
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ cd ..
jdixo001@hammer.cs.ucr.edu:~/Documents $ ls
firstrepo  lab	rshell	test  ucr-cs100
jdixo001@hammer.cs.ucr.edu:~/Documents $ cd /
jdixo001@hammer.cs.ucr.edu:/ $ ls
bin  boot  cgroup  class  C:\nppdf32Log\debuglog.txt  dev  etc	extra  home  lib  lib64  lost+found  media  misc  mnt  net  opt  proc  root  sbin  selinux  srv  sys  tmp  usr	var
jdixo001@hammer.cs.ucr.edu:/ $ cd home/csmajs/jdixo01 01/Documents/rhs  shell  /
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/ $ ls
a.out  bin  infinite.cpp  LICENSE  Makefile  README.md	src  tests
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/ $ cd -
jdixo001@hammer.cs.ucr.edu:/ $ ls
bin  boot  cgroup  class  C:\nppdf32Log\debuglog.txt  dev  etc	extra  home  lib  lib64  lost+found  media  misc  mnt  net  opt  proc  root  sbin  selinux  srv  sys  tmp  usr	var
jdixo001@hammer.cs.ucr.edu:/ $ cd -
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/ $ cd ~
jdixo001@hammer.cs.ucr.edu:~ $ cd -
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/ $ cd
jdixo001@hammer.cs.ucr.edu:~ $ cd ~/Desktop
jdixo001@hammer.cs.ucr.edu:~/Desktop $ ls
rshell	untitled folder  WordLadder.cc	WordLadder.h  WordLadder.h~  WordLadder.h.gch
jdixo001@hammer.cs.ucr.edu:~/Desktop $ cd ~/Documents/rshell/bin
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/bin $ ls
cp  ls	mv  rm	rshell
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell/bin $ cd ..
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ #Demonstraing CTRL-C 
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ cat 
test
test
^C00x7fffd8538c00C
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ # ./a.out #infinite loop to demonstrate ctrl-c further
^C00x7fffd8538c00C
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ ps
  PID TTY          TIME CMD
29220 pts/77   00:00:00 bash
29239 pts/77   00:00:00 rshell
29804 pts/77   00:00:00 ps
jdixo001@hammer.cs.ucr.edu:~/Documents/rshell $ cd								..
jdixo001@hammer.cs.ucr.edu:~/Documents $ #end
jdixo001@hammer.cs.ucr.edu:~/Documents $ exit
~/Documents/rshell
jdixo001@hammer $ exit
exit

Script done on Fri 29 May 2015 10:12:47 PM PDT
